//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IncomeInsightEngine.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IncomeInsightEngine.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add a single transaction ähnelt.
        /// </summary>
        public static string Addasingletransaction {
            get {
                return ResourceManager.GetString("Addasingletransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add more Details ähnelt.
        /// </summary>
        public static string AddMoreDetails {
            get {
                return ResourceManager.GetString("AddMoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add transactions ähnelt.
        /// </summary>
        public static string AddTransactions {
            get {
                return ResourceManager.GetString("AddTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All ähnelt.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Amount ähnelt.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analyze Groups ähnelt.
        /// </summary>
        public static string AnalyzeGroups {
            get {
                return ResourceManager.GetString("AnalyzeGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analyze transactions ähnelt.
        /// </summary>
        public static string AnalyzeTransactions {
            get {
                return ResourceManager.GetString("AnalyzeTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply ähnelt.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ascending ähnelt.
        /// </summary>
        public static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bank Transfer ähnelt.
        /// </summary>
        public static string BankTransfer {
            get {
                return ResourceManager.GetString("BankTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Batch processing ähnelt.
        /// </summary>
        public static string BatchProcessing {
            get {
                return ResourceManager.GetString("BatchProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Batch processing of partner names ähnelt.
        /// </summary>
        public static string BatchProcessingOfPartnerNames {
            get {
                return ResourceManager.GetString("BatchProcessingOfPartnerNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blank ähnelt.
        /// </summary>
        public static string Blank {
            get {
                return ResourceManager.GetString("Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Budget Categories ähnelt.
        /// </summary>
        public static string BudgetCategories {
            get {
                return ResourceManager.GetString("BudgetCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Budget Category ähnelt.
        /// </summary>
        public static string BudgetCategory {
            get {
                return ResourceManager.GetString("BudgetCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate Average Amount ähnelt.
        /// </summary>
        public static string CalculateAverageAmount {
            get {
                return ResourceManager.GetString("CalculateAverageAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate Average Expense ähnelt.
        /// </summary>
        public static string CalculateAverageExpense {
            get {
                return ResourceManager.GetString("CalculateAverageExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate Average Income ähnelt.
        /// </summary>
        public static string CalculateAverageIncome {
            get {
                return ResourceManager.GetString("CalculateAverageIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate Grouped Amount ähnelt.
        /// </summary>
        public static string CalculateGroupedAmount {
            get {
                return ResourceManager.GetString("CalculateGroupedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate Grouped Average Amount ähnelt.
        /// </summary>
        public static string CalculateGroupedAverageAmount {
            get {
                return ResourceManager.GetString("CalculateGroupedAverageAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate Grouped Average Expense ähnelt.
        /// </summary>
        public static string CalculateGroupedAverageExpense {
            get {
                return ResourceManager.GetString("CalculateGroupedAverageExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate Grouped Average Income ähnelt.
        /// </summary>
        public static string CalculateGroupedAverageIncome {
            get {
                return ResourceManager.GetString("CalculateGroupedAverageIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate Grouped Expenses ähnelt.
        /// </summary>
        public static string CalculateGroupedExpenses {
            get {
                return ResourceManager.GetString("CalculateGroupedExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate Grouped Income ähnelt.
        /// </summary>
        public static string CalculateGroupedIncome {
            get {
                return ResourceManager.GetString("CalculateGroupedIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate Grouped Percentage Of Total Expanses ähnelt.
        /// </summary>
        public static string CalculateGroupedPercentageOfTotalExpanses {
            get {
                return ResourceManager.GetString("CalculateGroupedPercentageOfTotalExpanses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate Grouped Percentage Of Total Income ähnelt.
        /// </summary>
        public static string CalculateGroupedPercentageOfTotalIncome {
            get {
                return ResourceManager.GetString("CalculateGroupedPercentageOfTotalIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate Median ähnelt.
        /// </summary>
        public static string CalculateMedian {
            get {
                return ResourceManager.GetString("CalculateMedian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate Mode ähnelt.
        /// </summary>
        public static string CalculateMode {
            get {
                return ResourceManager.GetString("CalculateMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate Quantile ähnelt.
        /// </summary>
        public static string CalculateQuantile {
            get {
                return ResourceManager.GetString("CalculateQuantile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate Standard Deviation ähnelt.
        /// </summary>
        public static string CalculateStandardDeviation {
            get {
                return ResourceManager.GetString("CalculateStandardDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate Total Amount ähnelt.
        /// </summary>
        public static string CalculateTotalAmount {
            get {
                return ResourceManager.GetString("CalculateTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate Total Expenses ähnelt.
        /// </summary>
        public static string CalculateTotalExpenses {
            get {
                return ResourceManager.GetString("CalculateTotalExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate Total Income ähnelt.
        /// </summary>
        public static string CalculateTotalIncome {
            get {
                return ResourceManager.GetString("CalculateTotalIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate Variance ähnelt.
        /// </summary>
        public static string CalculateVariance {
            get {
                return ResourceManager.GetString("CalculateVariance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cash ähnelt.
        /// </summary>
        public static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Categories ähnelt.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Category ähnelt.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change ähnelt.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose Mode ähnelt.
        /// </summary>
        public static string ChooseMode {
            get {
                return ResourceManager.GetString("ChooseMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Classification ähnelt.
        /// </summary>
        public static string Classification {
            get {
                return ResourceManager.GetString("Classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Classifications ähnelt.
        /// </summary>
        public static string Classifications {
            get {
                return ResourceManager.GetString("Classifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Completed ähnelt.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Complete view ähnelt.
        /// </summary>
        public static string CompleteView {
            get {
                return ResourceManager.GetString("CompleteView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Console mode ähnelt.
        /// </summary>
        public static string ConsoleMode {
            get {
                return ResourceManager.GetString("ConsoleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Credit Card ähnelt.
        /// </summary>
        public static string CreditCard {
            get {
                return ResourceManager.GetString("CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cryptocurrency ähnelt.
        /// </summary>
        public static string Cryptocurrency {
            get {
                return ResourceManager.GetString("Cryptocurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Currencies ähnelt.
        /// </summary>
        public static string Currencies {
            get {
                return ResourceManager.GetString("Currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Currency ähnelt.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Currently ähnelt.
        /// </summary>
        public static string Currently {
            get {
                return ResourceManager.GetString("Currently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current partner name ähnelt.
        /// </summary>
        public static string CurrentPartnerName {
            get {
                return ResourceManager.GetString("CurrentPartnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Debit Card ähnelt.
        /// </summary>
        public static string DebitCard {
            get {
                return ResourceManager.GetString("DebitCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Transaction ähnelt.
        /// </summary>
        public static string DeleteTransaction {
            get {
                return ResourceManager.GetString("DeleteTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Descending ähnelt.
        /// </summary>
        public static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Direct Debit ähnelt.
        /// </summary>
        public static string DirectDebit {
            get {
                return ResourceManager.GetString("DirectDebit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Transactions ähnelt.
        /// </summary>
        public static string EditTransactions {
            get {
                return ResourceManager.GetString("EditTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End ähnelt.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EndDate ähnelt.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter new ähnelt.
        /// </summary>
        public static string EnterNew {
            get {
                return ResourceManager.GetString("EnterNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter new name ähnelt.
        /// </summary>
        public static string EnterNewName {
            get {
                return ResourceManager.GetString("EnterNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter path ähnelt.
        /// </summary>
        public static string EnterPath {
            get {
                return ResourceManager.GetString("EnterPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter the quantile value (between 0 and 1): ähnelt.
        /// </summary>
        public static string EnterQuantile {
            get {
                return ResourceManager.GetString("EnterQuantile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occurred ähnelt.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A cryptographic error occurred ähnelt.
        /// </summary>
        public static string ErrorCryptograpic {
            get {
                return ResourceManager.GetString("ErrorCryptograpic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expenses ähnelt.
        /// </summary>
        public static string Expenses {
            get {
                return ResourceManager.GetString("Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter options ähnelt.
        /// </summary>
        public static string FilterOptions {
            get {
                return ResourceManager.GetString("FilterOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finish ähnelt.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frequencies ähnelt.
        /// </summary>
        public static string Frequencies {
            get {
                return ResourceManager.GetString("Frequencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frequency ähnelt.
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get All Transactions ähnelt.
        /// </summary>
        public static string GetAllTransactions {
            get {
                return ResourceManager.GetString("GetAllTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get Expense Transactions ähnelt.
        /// </summary>
        public static string GetExpenseTransactions {
            get {
                return ResourceManager.GetString("GetExpenseTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get Income Transactions ähnelt.
        /// </summary>
        public static string GetIncomeTransactions {
            get {
                return ResourceManager.GetString("GetIncomeTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get Reimbursable Transactions ähnelt.
        /// </summary>
        public static string GetReimbursableTransactions {
            get {
                return ResourceManager.GetString("GetReimbursableTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get Tax Deductible Transactions ähnelt.
        /// </summary>
        public static string GetTaxDeductibleTransactions {
            get {
                return ResourceManager.GetString("GetTaxDeductibleTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get Transactions By Amount Range ähnelt.
        /// </summary>
        public static string GetTransactionsByAmountRange {
            get {
                return ResourceManager.GetString("GetTransactionsByAmountRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get Transactions By Budget Category ähnelt.
        /// </summary>
        public static string GetTransactionsByBudgetCategory {
            get {
                return ResourceManager.GetString("GetTransactionsByBudgetCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get Transactions By Category ähnelt.
        /// </summary>
        public static string GetTransactionsByCategory {
            get {
                return ResourceManager.GetString("GetTransactionsByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get Transactions By Classification ähnelt.
        /// </summary>
        public static string GetTransactionsByClassification {
            get {
                return ResourceManager.GetString("GetTransactionsByClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get Transactions By Currency ähnelt.
        /// </summary>
        public static string GetTransactionsByCurrency {
            get {
                return ResourceManager.GetString("GetTransactionsByCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get Transactions By Date ähnelt.
        /// </summary>
        public static string GetTransactionsByDate {
            get {
                return ResourceManager.GetString("GetTransactionsByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get Transactions By Description ähnelt.
        /// </summary>
        public static string GetTransactionsByDescription {
            get {
                return ResourceManager.GetString("GetTransactionsByDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get Transactions By Exact Amount ähnelt.
        /// </summary>
        public static string GetTransactionsByExactAmount {
            get {
                return ResourceManager.GetString("GetTransactionsByExactAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get Transactions By Frequency ähnelt.
        /// </summary>
        public static string GetTransactionsByFrequency {
            get {
                return ResourceManager.GetString("GetTransactionsByFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get Transactions By Location ähnelt.
        /// </summary>
        public static string GetTransactionsByLocation {
            get {
                return ResourceManager.GetString("GetTransactionsByLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get Transactions By Partner ähnelt.
        /// </summary>
        public static string GetTransactionsByPartner {
            get {
                return ResourceManager.GetString("GetTransactionsByPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get Transactions By Payment Method ähnelt.
        /// </summary>
        public static string GetTransactionsByPaymentMethod {
            get {
                return ResourceManager.GetString("GetTransactionsByPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get Transactions By Priority ähnelt.
        /// </summary>
        public static string GetTransactionsByPriority {
            get {
                return ResourceManager.GetString("GetTransactionsByPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get Transactions By Project ähnelt.
        /// </summary>
        public static string GetTransactionsByProject {
            get {
                return ResourceManager.GetString("GetTransactionsByProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get Transactions By Status ähnelt.
        /// </summary>
        public static string GetTransactionsByStatus {
            get {
                return ResourceManager.GetString("GetTransactionsByStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get Transactions By Tag ähnelt.
        /// </summary>
        public static string GetTransactionsByTag {
            get {
                return ResourceManager.GetString("GetTransactionsByTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group ähnelt.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group By ähnelt.
        /// </summary>
        public static string GroupBy {
            get {
                return ResourceManager.GetString("GroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group By Amount ähnelt.
        /// </summary>
        public static string GroupByAmount {
            get {
                return ResourceManager.GetString("GroupByAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group By Amountrange ähnelt.
        /// </summary>
        public static string GroupByAmountrange {
            get {
                return ResourceManager.GetString("GroupByAmountrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group By Budget Category ähnelt.
        /// </summary>
        public static string GroupByBudgetCategory {
            get {
                return ResourceManager.GetString("GroupByBudgetCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group By Category ähnelt.
        /// </summary>
        public static string GroupByCategory {
            get {
                return ResourceManager.GetString("GroupByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group By Classification ähnelt.
        /// </summary>
        public static string GroupByClassification {
            get {
                return ResourceManager.GetString("GroupByClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group By Currency ähnelt.
        /// </summary>
        public static string GroupByCurrency {
            get {
                return ResourceManager.GetString("GroupByCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group By Date ähnelt.
        /// </summary>
        public static string GroupByDate {
            get {
                return ResourceManager.GetString("GroupByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group By Day ähnelt.
        /// </summary>
        public static string GroupByDateDay {
            get {
                return ResourceManager.GetString("GroupByDateDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group By Month ähnelt.
        /// </summary>
        public static string GroupByDateMonth {
            get {
                return ResourceManager.GetString("GroupByDateMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group By Weekday ähnelt.
        /// </summary>
        public static string GroupByDateWeekDay {
            get {
                return ResourceManager.GetString("GroupByDateWeekDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group By Year ähnelt.
        /// </summary>
        public static string GroupByDateYear {
            get {
                return ResourceManager.GetString("GroupByDateYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group By Description ähnelt.
        /// </summary>
        public static string GroupByDescription {
            get {
                return ResourceManager.GetString("GroupByDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group By Frequency ähnelt.
        /// </summary>
        public static string GroupByFrequency {
            get {
                return ResourceManager.GetString("GroupByFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group By Location ähnelt.
        /// </summary>
        public static string GroupByLocation {
            get {
                return ResourceManager.GetString("GroupByLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group By Notes ähnelt.
        /// </summary>
        public static string GroupByNotes {
            get {
                return ResourceManager.GetString("GroupByNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group By Partner ähnelt.
        /// </summary>
        public static string GroupByPartner {
            get {
                return ResourceManager.GetString("GroupByPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group By Partner IBAN ähnelt.
        /// </summary>
        public static string GroupByPartnerIBAN {
            get {
                return ResourceManager.GetString("GroupByPartnerIBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group By Payment Method ähnelt.
        /// </summary>
        public static string GroupByPaymentMethod {
            get {
                return ResourceManager.GetString("GroupByPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group By Priority ähnelt.
        /// </summary>
        public static string GroupByPriority {
            get {
                return ResourceManager.GetString("GroupByPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group By Project ähnelt.
        /// </summary>
        public static string GroupByProject {
            get {
                return ResourceManager.GetString("GroupByProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group By Status ähnelt.
        /// </summary>
        public static string GroupByStatus {
            get {
                return ResourceManager.GetString("GroupByStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group By Tag ähnelt.
        /// </summary>
        public static string GroupByTag {
            get {
                return ResourceManager.GetString("GroupByTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home ähnelt.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ID ähnelt.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import csv file from DKB ähnelt.
        /// </summary>
        public static string importcsvfilefromDKB {
            get {
                return ResourceManager.GetString("importcsvfilefromDKB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Income ähnelt.
        /// </summary>
        public static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid quantile value. Please enter a value between 0 and 1. ähnelt.
        /// </summary>
        public static string InvalidQuantile {
            get {
                return ResourceManager.GetString("InvalidQuantile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invoice ähnelt.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Location ähnelt.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Locations ähnelt.
        /// </summary>
        public static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max. amount ähnelt.
        /// </summary>
        public static string MaxAmount {
            get {
                return ResourceManager.GetString("MaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Min. amount ähnelt.
        /// </summary>
        public static string MinAmount {
            get {
                return ResourceManager.GetString("MinAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notes ähnelt.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die no transactions available ähnelt.
        /// </summary>
        public static string notransactionsavailable {
            get {
                return ResourceManager.GetString("notransactionsavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Partner ähnelt.
        /// </summary>
        public static string Partner {
            get {
                return ResourceManager.GetString("Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Partner IBAN ähnelt.
        /// </summary>
        public static string PartnerIBAN {
            get {
                return ResourceManager.GetString("PartnerIBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Partners ähnelt.
        /// </summary>
        public static string Partners {
            get {
                return ResourceManager.GetString("Partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Payment Method ähnelt.
        /// </summary>
        public static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Payment Methods ähnelt.
        /// </summary>
        public static string PaymentMethods {
            get {
                return ResourceManager.GetString("PaymentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PayPal ähnelt.
        /// </summary>
        public static string PayPal {
            get {
                return ResourceManager.GetString("PayPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pending ähnelt.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Priorities ähnelt.
        /// </summary>
        public static string Priorities {
            get {
                return ResourceManager.GetString("Priorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Priority ähnelt.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project ähnelt.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projects ähnelt.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Receipt ähnelt.
        /// </summary>
        public static string Receipt {
            get {
                return ResourceManager.GetString("Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refine selection ähnelt.
        /// </summary>
        public static string RefineSelection {
            get {
                return ResourceManager.GetString("RefineSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reimbursable ähnelt.
        /// </summary>
        public static string Reimbursable {
            get {
                return ResourceManager.GetString("Reimbursable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset ähnelt.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Result ähnelt.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selection ähnelt.
        /// </summary>
        public static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Separated by commas &apos;,&apos; ähnelt.
        /// </summary>
        public static string SeparatedByCommas {
            get {
                return ResourceManager.GetString("SeparatedByCommas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Short view ähnelt.
        /// </summary>
        public static string ShortView {
            get {
                return ResourceManager.GetString("ShortView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show ähnelt.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort ähnelt.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort by Amount ähnelt.
        /// </summary>
        public static string SortByAmount {
            get {
                return ResourceManager.GetString("SortByAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort By Amount Ascending ähnelt.
        /// </summary>
        public static string SortByAmountAscending {
            get {
                return ResourceManager.GetString("SortByAmountAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort By Amount Descending ähnelt.
        /// </summary>
        public static string SortByAmountDescending {
            get {
                return ResourceManager.GetString("SortByAmountDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort by Date ähnelt.
        /// </summary>
        public static string SortByDate {
            get {
                return ResourceManager.GetString("SortByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort by ID ähnelt.
        /// </summary>
        public static string SortById {
            get {
                return ResourceManager.GetString("SortById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort By Key Ascending ähnelt.
        /// </summary>
        public static string SortByKeyAscending {
            get {
                return ResourceManager.GetString("SortByKeyAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort By Key Descending ähnelt.
        /// </summary>
        public static string SortByKeyDescending {
            get {
                return ResourceManager.GetString("SortByKeyDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort by Location ähnelt.
        /// </summary>
        public static string SortByLocation {
            get {
                return ResourceManager.GetString("SortByLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort by Partner ähnelt.
        /// </summary>
        public static string SortByPartner {
            get {
                return ResourceManager.GetString("SortByPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorting options ähnelt.
        /// </summary>
        public static string SortingOptions {
            get {
                return ResourceManager.GetString("SortingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort By Amount Ascending ähnelt.
        /// </summary>
        public static string SortTransactionsByAmountAscending {
            get {
                return ResourceManager.GetString("SortTransactionsByAmountAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort By Amount Descending ähnelt.
        /// </summary>
        public static string SortTransactionsByAmountDescending {
            get {
                return ResourceManager.GetString("SortTransactionsByAmountDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort By Date Ascending ähnelt.
        /// </summary>
        public static string SortTransactionsByDateAscending {
            get {
                return ResourceManager.GetString("SortTransactionsByDateAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort By Date Descending ähnelt.
        /// </summary>
        public static string SortTransactionsByDateDescending {
            get {
                return ResourceManager.GetString("SortTransactionsByDateDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort By Id Ascending ähnelt.
        /// </summary>
        public static string SortTransactionsByIdAscending {
            get {
                return ResourceManager.GetString("SortTransactionsByIdAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort By Id Descending ähnelt.
        /// </summary>
        public static string SortTransactionsByIdDescending {
            get {
                return ResourceManager.GetString("SortTransactionsByIdDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort By Location Ascending ähnelt.
        /// </summary>
        public static string SortTransactionsByLocationAscending {
            get {
                return ResourceManager.GetString("SortTransactionsByLocationAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort By Location Descending ähnelt.
        /// </summary>
        public static string SortTransactionsByLocationDescending {
            get {
                return ResourceManager.GetString("SortTransactionsByLocationDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort By Partner Ascending ähnelt.
        /// </summary>
        public static string SortTransactionsByPartnerAscending {
            get {
                return ResourceManager.GetString("SortTransactionsByPartnerAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort By Partner Descending ähnelt.
        /// </summary>
        public static string SortTransactionsByPartnerDescending {
            get {
                return ResourceManager.GetString("SortTransactionsByPartnerDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Date ähnelt.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status ähnelt.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Statuses ähnelt.
        /// </summary>
        public static string Statuses {
            get {
                return ResourceManager.GetString("Statuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tag ähnelt.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tags ähnelt.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tax Deductible ähnelt.
        /// </summary>
        public static string TaxDeductible {
            get {
                return ResourceManager.GetString("TaxDeductible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text ähnelt.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total amount ähnelt.
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total expenses ähnelt.
        /// </summary>
        public static string TotalExpenses {
            get {
                return ResourceManager.GetString("TotalExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total income ähnelt.
        /// </summary>
        public static string TotalIncome {
            get {
                return ResourceManager.GetString("TotalIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transaction ähnelt.
        /// </summary>
        public static string Transaction {
            get {
                return ResourceManager.GetString("Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transactions ähnelt.
        /// </summary>
        public static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View ähnelt.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View list ähnelt.
        /// </summary>
        public static string ViewList {
            get {
                return ResourceManager.GetString("ViewList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View Only Groupnames ähnelt.
        /// </summary>
        public static string ViewOnlyGroupnames {
            get {
                return ResourceManager.GetString("ViewOnlyGroupnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View transactions ähnelt.
        /// </summary>
        public static string ViewTransactions {
            get {
                return ResourceManager.GetString("ViewTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Voucher ähnelt.
        /// </summary>
        public static string Voucher {
            get {
                return ResourceManager.GetString("Voucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
